jobs:  
- deployment: VMDeploy
  displayName: web
  environment:
    name:  vm
    resourceType: VirtualMachine
    tags: web1
  strategy:
    runOnce:
      deploy:
        steps:
        - task: CopyFiles@2
          inputs:
            contents: '**'
            targetFolder: '/home/azureuser/Ava/'
            overWrite: true
        - script: |
            cd /home/azureuser/Ava
            source virtualenv_name/bin/activate
            pip install -r reqirements.txt

        - script: python ava.py
          displayName: 'Run a multi-line script'
